import { Injectable } from '@angular/core';

/**
 * This service is populated by the 'codekeys' component (which in turn is
 * generated by XLIFF processing).
 */
@Injectable()
export class TranslatorService {

    private keyMap: Object = {};

    constructor() { }

    add( key: string, translation: string ) {
        this.keyMap[key] = translation;
    }

    lookup( key: string ): string {
        return this.keyMap.hasOwnProperty( key ) ? this.keyMap[key] : key;
    }

}
